import React from 'react'

const Term = () => {
    return (
        <div>
            <h1>TERMS OF SERVICE WEBSITE TERMS OF USE</h1>
            <h1>PLEASE READ CAREFULLY BEFORE USING THIS WEBSITE.</h1>
            <h1>THIS TERMS OF USE AGREEMENT (TOGETHER WITH THE DOCUMENTS REFERRED TO IN IT) (THE “TERMS OF USE” OR THE “AGREEMENT”) IS A LEGAL AGREEMENT BETWEEN YOU AND THE SELLER (“SELLER”, “US” OR “WE”) FOR USE OF OUR WEBSITE (THE “WEBSITE”), AND THE PURCHASE OF PRODUCTS FROM US.</h1>
            <h1>BY USING THE WEBSITE AND/OR PURCHASING GOODS FROM US, YOU MUST READ, AGREE WITH AND ACCEPT ALL OF THE TERMS AND CONDITIONS CONTAINED IN THIS AGREEMENT. THIS AGREEMENT IS PROVIDED TO YOU AND CONCLUDED IN ENGLISH. YOU AGREE THAT ANY USE BY YOU OF THE WEBSITE AND/OR THE PURCHASE OF GOODS THROUGH THE WEBSITE SHALL CONSTITUTE YOUR ACCEPTANCE OF THE AGREEMENT. IF YOU DO NOT AGREE TO THE TERMS OF THIS AGREEMENT, PLEASE REFRAIN FROM USING THE WEBSITE.</h1>
            <h1>1.1 IN CONSIDERATION OF YOU AGREEING TO ABIDE BY THE TERMS OF THIS AGREEMENT, WE HEREBY GRANT TO YOU A NON-EXCLUSIVE, NON-TRANSFERABLE, LICENCE TO USE THE WEBSITE ON THE TERMS OF THIS AGREEMENT.</h1>
            <h1>1.2 ACCESS TO THE WEBSITE IS PERMITTED ON A TEMPORARY BASIS FOR YOUR PRIVATE PURPOSES ONLY AND WE RESERVE THE RIGHT TO WITHDRAW OR AMEND THE SERVICE WE PROVIDE ON THE WEBSITE WITHOUT NOTICE. WE WILL NOT BE LIABLE IF FOR ANY REASON THE WEBSITE IS UNAVAILABLE AT ANY TIME OR FOR ANY PERIOD.</h1>
        </div>
    )
}

export default Term